export const REGEX = {
  NUMBER: /^(?:(?:\+|0{0,2})91(\s*[\-]\s*)?|[0]?)?[789]\d{9}$/,
  ONLY_NUMBER: /^\d+$/,
  ONLY_ALPHABET: /^[a-zA-Z]*$/,
  START_WITH_ALPHABET_ENDS_WITH_DIGITS: /^[a-zA-Z]{4}[0-9]{4}$/,
  AMOUNT: /(^[0][1-9]+)|([1-9]\d*)+$/,
  EMAIL: /^\w+([.-]\w+)*@\w+([.-]\w+)*\.\w{2,5}$/i,
  PASSWORD: /(?=[^A-Z]*[A-Z])(?=[^a-z]*[a-z])(?=.*[@#$%^&+=])(?=[^0-9]*[0-9]).{8,20}/,
  URL: /^(http|https):\/\/(([a-zA-Z0-9$\-_.+!*'(),;:&=]|%[0-9a-fA-F]{2})+@)?(((25[0-5]|2[0-4][0-9]|[0-1][0-9][0-9]|[1-9][0-9]|[0-9])(\.(25[0-5]|2[0-4][0-9]|[0-1][0-9][0-9]|[1-9][0-9]|[0-9])){3})|localhost|([a-zA-Z0-9\-\u00C0-\u017F]+\.)+([a-zA-Z]{2,}))(:[0-9]+)?(\/(([a-zA-Z0-9$\-_.+!*'(),;:@&=]|%[0-9a-fA-F]{2})*(\/([a-zA-Z0-9$\-_.+!*'(),;:@&=]|%[0-9a-fA-F]{2})*)*)?(\?([a-zA-Z0-9$\-_.+!*'(),;:@&=\/?]|%[0-9a-fA-F]{2})*)?(\#([a-zA-Z0-9$\-_.+!*'(),;:@&=\/?]|%[0-9a-fA-F]{2})*)?)?$/
};

export const LIMIT = {
  MAX_SHORT_NAME_LENGTH: 10,
  MIN_SHORT_NAME_LENGTH: 3,
  MAX_NAME_LENGTH: 50,
  MAX_DOMAIN_LENGTH: 20,
  MAX_NAME_LENGTH_VI: 80,
  CURRENT_VERSION_LENGTH: 20,
  MAX_INTEREST_LENGTH: 35,
  MAX_INTEREST_LENGTH_VI: 50,
  MIN_NAME_LENGTH: 3,
  MAX_EMAIL_LENGTH: 120,
  MAX_PASSWORD_LENGTH: 20,
  DESCRIPTION_MAX: 1000,
  DESCRIPTION_MAX_VI: 1200,
  MAX_MOBILE_LENGTH: 15,
  MIN_MOBILE_LENGTH: 9,
  NOTE_MAX: 300,
  VIETNAMESE_NOTE_MAX: 500,
  MAX_PARTICIPANTS_LENGTH: 6,
  MAX_POINTS_LENGTH: 10,
  MAX_CLIENT_CLUB_POINTS_LENGTH: 15,
  MAX_DISPLAY_ORDER_LENGTH: 3,
  MAX_CODE_LENGTH: 30,
  MIN_CODE_LENGTH: 2,
  MAX_CODE_QUANTITY_LENGTH: 4,
  MAX_QR_CODE_LENGTH: 8,
  MAX_TAX_CODE_LENGTH: 15,
  MAX_STEP_LENGTH: 10,
  MAX_QUESTION_LENGTH: 1000,
  MAX_AGE_QUES_LENGTH: 300,
  MAX_AGE_QUES_LENGTH_VI: 350,
  MAX_AGE_ANS_LENGTH: 200,
  MAX_AGE_ANS_LENGTH_VI: 250,
  MAX_LWC_POINTS: 6,
  MAX_DAYS: 5,
  MAX_DISCOUNT: 3,
  MAX_PERCENTAGE_WITH_NEGATIVE: 4,
  MAX_DISCOUNT_VALUE: 100
};
